"""Regenerate the standalone notebook from the same source used by the local CLI."""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MODULES = ["__init__.py", "data.py", "training.py", "fast_training.py", "prediction.py"]


def build():
    cells = []

    def markdown(source):
        cells.append({"cell_type": "markdown", "metadata": {}, "source": source.splitlines(True)})

    def code(source, tag):
        cells.append({"cell_type": "code", "execution_count": None, "outputs": [],
                      "metadata": {"tags": [tag]}, "source": source.splitlines(True)})

    markdown("""# Fast credit-card fraud training — one model per cell

The old notebook performed **52 fits** (48 CV fits + 4 refits). This notebook defaults
to **3 fits**, no grid search, and early stopping for boosting. XGBoost uses the T4;
Logistic Regression and LightGBM use CPU. The full dataset is retained.

Each model has its own cell and checkpoint. Run top to bottom; use `RESUME = True`
with the **same RUN_NAME and settings** to reuse completed models after interruption.
Only the active unfinished model must restart. Drive persistence is optional.

Outputs: CPU-ready model, evaluation CSVs, plots, dataset fingerprint, dependency versions,
resume bullets, and a ZIP compatible with this project's API/dashboard.
No measured GPU results are pre-filled. Never use synthetic smoke-test metrics on a resume.
""")
    markdown("## 1. Install once\nIf packages were already imported, restart the runtime after installation.")
    code('%pip install -q "numpy>=1.26,<3" "pandas>=2.2,<3" "scikit-learn>=1.6,<2" '
         '"xgboost>=2.1,<4" "lightgbm>=4.5,<5" "joblib>=1.4,<2" '
         '"matplotlib>=3.9,<4" "kagglehub>=0.3,<1"\n', "install")
    markdown("""## 2. Configure
Start with `MODELS = ('xgboost',)` if you want just one model. For the three-model
comparison keep the default. Unselected model cells will skip automatically.
Do not change model choices after seeing test results; use validation for development.

Keep a stable run name when resuming. Use a new name for changed settings.
Enable Drive to preserve checkpoints across Colab disconnects. Authorization may
require the Colab browser rather than the VS Code extension. Without Drive, download
the ZIP before the runtime is deleted. Windows paths are not available on Colab.
""")
    code('''import os
from pathlib import Path

DEVICE = "cuda"  # Colab T4; use "cpu" locally
MODELS = ("logistic_regression", "xgboost", "lightgbm")
SEED = 42
JOBS = min(2, os.cpu_count() or 1)
MAX_TREES = 300
PATIENCE = 30
MIN_PRECISION = 0.80
DATA_SOURCE = "kaggle"  # or "path"
DATA_PATH = Path("/content/drive/MyDrive/fraud-detection/creditcard.csv")
SAVE_TO_DRIVE = False
RUN_NAME = "fast-01"  # Keep unchanged when resuming this run
RESUME = True

if SAVE_TO_DRIVE:
    from google.colab import drive
    drive.mount("/content/drive")
    OUTPUT_ROOT = Path("/content/drive/MyDrive/fraud-detection/runs")
else:
    OUTPUT_ROOT = Path("/content/fraud-detection/runs")
OUTPUT_DIR = OUTPUT_ROOT / RUN_NAME
print("Results:", OUTPUT_DIR)
''', "config")
    markdown("""## 3. Load the project training code
The exact local training modules are embedded below so this notebook runs standalone.
This cell only installs project source into a temporary folder; it does not train.
The notebook is generated by `scripts/build_notebook.py` to prevent local/Colab drift.
""")
    sources = {name: (ROOT / "src" / "fraud_detection" / name).read_text(encoding="utf-8")
               for name in MODULES}
    code('''import importlib
import sys
import tempfile
from pathlib import Path

PROJECT_SOURCES = ''' + repr(sources) + '''
source_root = Path(tempfile.mkdtemp(prefix="fraud-training-"))
package = source_root / "fraud_detection"
package.mkdir()
for name, source in PROJECT_SOURCES.items():
    (package / name).write_text(source, encoding="utf-8", newline="\\n")
sys.path.insert(0, str(source_root))
for name in list(sys.modules):
    if name == "fraud_detection" or name.startswith("fraud_detection."):
        del sys.modules[name]
importlib.invalidate_caches()
from fraud_detection.fast_training import prepare_run, fit_model, finish_run
print("Project code ready.")
''', "bootstrap")
    markdown("""## 4. Locate dataset, validate GPU, prepare splits
Kaggle download is cached. If authentication is required, run `kagglehub.login()`
interactively; do not store tokens in this notebook.

Exact-feature duplicates are removed before stratified 70/15/15 train/validation/test
splitting. Boosters fit on 85% of **training**, using its remaining 15% for early stopping.
Validation selects model and threshold; test is used only in step 8.
""")
    code('''if DATA_SOURCE == "kaggle":
    import kagglehub
    DATA_PATH = Path(kagglehub.dataset_download("mlg-ulb/creditcardfraud")) / "creditcard.csv"
elif DATA_SOURCE != "path":
    raise ValueError("DATA_SOURCE must be kaggle or path")

run = prepare_run(DATA_PATH, OUTPUT_DIR, seed=SEED, jobs=JOBS,
                  min_precision=MIN_PRECISION, device=DEVICE, models=MODELS,
                  max_trees=MAX_TREES, patience=PATIENCE, resume=RESUME)
''', "prepare")
    for number, name, explanation in [
        (5, "logistic_regression", "CPU baseline, scaling fitted on training only."),
        (6, "xgboost", "T4/CUDA histogram trees; stop after 30 rounds without improvement by default."),
        (7, "lightgbm", "Compact CPU histogram booster with early stopping."),
    ]:
        markdown(f"## {number}. {name.replace('_', ' ').title()}\n{explanation}\n"
                 "A completed checkpoint is loaded instead of fitting again.")
        code(f'if "{name}" in MODELS:\n    print(fit_model(run, "{name}"))\n'
             f'else:\n    print("Skipped {name}")\n', name)
    markdown("""## 8. Freeze selection, evaluate and export
Select by validation AP and select each threshold on validation. Then evaluate the
untouched test split. Accuracy, fraud precision/recall/F1, AP, ROC-AUC and confusion
counts are saved. Re-running a completed export returns saved metrics.

Do not optimize against these test numbers. Compare the all-legitimate baseline:
high accuracy alone is misleading. CPU export and reload predictions are verified.
""")
    code('''import pandas as pd
from IPython.display import Image, display

report = finish_run(run)
display(pd.DataFrame(report["test"]))
display(Image(filename=str(OUTPUT_DIR / "precision_recall.png")))
display(Image(filename=str(OUTPUT_DIR / f"confusion_{report['selected_model']}.png")))
print((OUTPUT_DIR / "resume_bullets.md").read_text(encoding="utf-8"))
''', "export")
    markdown("""## 9. Verify predictions and package only serving files
The archive excludes the raw dataset and training checkpoints. Keep the original
run folder/Drive checkpoints if you want to resume. Package versions are recorded;
verify the artifact in your local environment after transfer.
""")
    code('''import json
import zipfile
import joblib
from fraud_detection.prediction import score_frame
from fraud_detection.data import FEATURES

artifact = joblib.load(OUTPUT_DIR / "model.joblib")  # Only load your own trusted artifacts
display(score_frame(artifact, run["test"][FEATURES].iloc[:5]))
archive = OUTPUT_DIR.with_suffix(".zip")
with zipfile.ZipFile(archive, "w", zipfile.ZIP_DEFLATED) as bundle:
    for path in OUTPUT_DIR.iterdir():
        if path.is_file() and not path.name.endswith(".tmp"):
            bundle.write(path, path.name)
print("Download:", archive)
DOWNLOAD_IN_COLAB_BROWSER = False
if DOWNLOAD_IN_COLAB_BROWSER:
    from google.colab import files
    files.download(str(archive))
''', "package")
    markdown('''## 10. Run the model in the project (local PowerShell)
Extract the ZIP into a **new** folder, e.g. `artifacts/colab-fast`, preserving any local run.
Then run from the project root:

```powershell
.\\.venv\\Scripts\\python.exe -m pip install -r artifacts/colab-fast/requirements-model.txt
.\\run.ps1 -ModelPath artifacts/colab-fast/model.joblib
```

Open **http://127.0.0.1:8000** for the dashboard and **/docs** for the API.
The dashboard shows the matching report and can score held-out examples or a sample CSV.
For full-dataset CSV inference:

```powershell
.\\.venv\\Scripts\\python.exe -m fraud_detection.cli predict --model artifacts/colab-fast/model.joblib --data data/creditcard.csv --output predictions/scores.csv
```

Use `resume_bullets.md` for the measured values, explaining test size and fraud count.
These are historical random-split results, not real payment deployment evidence.
''')
    for i, cell in enumerate(cells):
        cell["id"] = f"fraud-fast-{i:02d}"
    return {"cells": cells, "metadata": {"kernelspec": {"display_name": "Python 3",
            "language": "python", "name": "python3"}, "language_info": {"name": "python"}},
            "nbformat": 4, "nbformat_minor": 5}


if __name__ == "__main__":
    target = ROOT / "notebooks" / "train_fraud_detection.ipynb"
    target.write_text(json.dumps(build(), indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
    print(target)
